export const filterGroups = [
  {
    key: "type",
    label: "类型",
    options: ["全部", "故事片", "广告", "纪录片", "短片", "动画", "实验影像"],
  },
  {
    key: "emotion",
    label: "情绪",
    options: ["全部", "温暖", "宁静", "怀旧", "孤独", "希望", "紧张", "治愈"],
  },
  {
    key: "lighting",
    label: "光影",
    options: [
      "全部",
      "自然光",
      "黄金时刻",
      "蓝调时刻",
      "室内暖光",
      "逆光",
      "柔光",
      "硬光",
    ],
  },
  {
    key: "movement",
    label: "运镜",
    options: ["全部", "固定镜头", "推镜头", "拉镜头", "摇镜头", "跟镜头", "升降镜头", "航拍"],
  },
];

export const storyboardItems = [
  {
    id: "tea-room",
    title: "竹影茶室",
    image: "/images/tea-room.png",
    duration: "00:12",
    kind: "视频",
    type: "短片",
    emotion: "宁静",
    lighting: "自然光",
    movement: "固定镜头",
    tags: ["宁静", "自然光", "固定镜头", "室内", "日常生活"],
    description:
      "清晨的茶室，竹影透过纱窗落在青瓷与木案上，空气中有茶香与墨的气息，万物安静而温柔。",
    prompt:
      "清晨，自然光透过纱窗洒入中式茶室，竹影摇曳，青瓷茶具、木案、宣纸与墨盏，\n空气中有茶与墨的气息。宁静的生活氛围，固定镜头，35mm 电影质感，浅景深，柔和色调。",
  },
  {
    id: "bamboo-path",
    title: "雾中竹径",
    image: "/images/bamboo-path.png",
    duration: "00:15",
    kind: "视频",
    type: "纪录片",
    emotion: "宁静",
    lighting: "柔光",
    movement: "推镜头",
    tags: ["薄雾", "竹林", "柔光", "推镜头"],
    description: "雨后的石径穿过竹林，薄雾掩住远处院门，画面安静而有进入感。",
    prompt:
      "雨后清晨，湿润石径穿过幽深竹林，薄雾笼罩远处的中式院门，镜头沿石径缓慢推进。柔和散射光，层次丰富，低饱和青绿色调，35mm 胶片颗粒。",
  },
  {
    id: "celadon-tea",
    title: "青瓷与手",
    image: "/images/celadon-tea.png",
    duration: "00:08",
    kind: "分镜",
    type: "广告",
    emotion: "温暖",
    lighting: "室内暖光",
    movement: "固定镜头",
    tags: ["特写", "青瓷", "手部", "浅景深"],
    description: "一只手缓慢靠近温热的青瓷盖碗，细小蒸汽在侧光中浮动。",
    prompt:
      "青瓷盖碗置于深色木质茶盘，人物手部缓慢进入画面，蒸汽被窗边侧光照亮。微距特写，浅景深，真实陶瓷开片纹理，温暖而克制。",
  },
  {
    id: "linen-breeze",
    title: "风过窗纱",
    image: "/images/linen-breeze.png",
    duration: "00:10",
    kind: "分镜",
    type: "实验影像",
    emotion: "治愈",
    lighting: "自然光",
    movement: "固定镜头",
    tags: ["窗纱", "风", "自然光", "留白"],
    description: "轻薄亚麻窗纱随风起伏，竹叶的影子像呼吸一样落在织物上。",
    prompt:
      "象牙色亚麻窗纱被微风轻轻吹动，纤细竹叶从画面右侧进入，柔和自然光在织物上留下移动的影子。固定镜头，大量留白，安静治愈。",
  },
  {
    id: "misty-lake",
    title: "湖上晨光",
    image: "/images/misty-lake.png",
    duration: "00:11",
    kind: "视频",
    type: "纪录片",
    emotion: "希望",
    lighting: "黄金时刻",
    movement: "航拍",
    tags: ["晨雾", "湖面", "远山", "航拍"],
    description: "第一束日光越过山脊，一叶小舟划开安静的湖面与晨雾。",
    prompt:
      "日出时分，层叠群山与薄雾环绕平静湖面，一叶木舟穿过金色反光。高位远景缓慢移动，空间开阔，淡金与青灰色调，电影感。",
  },
  {
    id: "mountain-figure",
    title: "云外远望",
    image: "/images/mountain-figure.png",
    duration: "00:09",
    kind: "分镜",
    type: "故事片",
    emotion: "孤独",
    lighting: "柔光",
    movement: "拉镜头",
    tags: ["人物", "远景", "薄雾", "拉镜头"],
    description: "身着灰绿色长衣的人站在山崖边，向雾海，渺小却坚定。",
    prompt:
      "清晨山巅，一位身着灰绿色长衣的人背对镜头，望向层叠山谷与云雾。镜头缓慢拉远，突出人物与广阔自然的比例，柔光，低饱和。",
  },
  {
    id: "bamboo-still",
    title: "一枝入室",
    image: "/images/bamboo-still.png",
    duration: "00:06",
    kind: "分镜",
    type: "广告",
    emotion: "宁静",
    lighting: "硬光",
    movement: "固定镜头",
    tags: ["静物", "竹枝", "陶器", "侧光"],
    description: "陶罐里的一枝竹被侧光照亮，在深色墙面前留下安静的影子。",
    prompt:
      "深色手工陶罐置于木架，一枝纤细竹叶向上舒展，窗边硬光斜射进来。极简静物构图，固定镜头，真实材质，高对比但色彩克制。",
  },
];

export const nightStoryboardItems = [
  {
    id: "night-cinema",
    title: "雨夜老电影院",
    image: "/images/night-cinema.png",
    duration: "00:12",
    kind: "视频",
    type: "故事片",
    emotion: "温暖",
    lighting: "自然光",
    movement: "固定镜头",
    tags: ["孤独", "低调光", "固定镜头", "室外", "夜晚街道"],
    description:
      "老电影院的雨夜，霓虹与路灯映在湿润的地面，空气里有潮湿与旧胶片的味道。一个人走在街道上，光影在脚下碎裂又重组。",
    prompt:
      "雨夜，老电影院门口，霓虹灯与路灯反射在湿漉漉的地面，孤独的人影，低调光，胶片质感，街道寂静，35mm 电影质感，浅景深，长焦压缩空间，缓慢推进。",
  },
  {
    id: "night-projector",
    title: "放映室的光",
    image: "/images/night-projector.png",
    duration: "00:15",
    kind: "视频",
    type: "纪录片",
    emotion: "怀旧",
    lighting: "硬光",
    movement: "推镜头",
    tags: ["放映机", "体积光", "剪影", "旧胶片"],
    description: "放映机的光束穿过尘埃，操作员与老式胶片盘沉在暗部里。",
    prompt:
      "昏暗老式放映室，人物背影位于画面左侧，放映机射出强烈体积光，尘埃颗粒可见，右侧有大型金属胶片盘，低调光，电影质感。",
  },
  {
    id: "night-lounge",
    title: "雨窗旧厅",
    image: "/images/night-lounge.png",
    duration: "00:08",
    kind: "分镜",
    type: "故事片",
    emotion: "温暖",
    lighting: "室内暖光",
    movement: "固定镜头",
    tags: ["旧公寓", "台灯", "雨窗", "暖光"],
    description: "无人坐下的旧客厅只亮着台灯，雨后的城市在窗外化成柔软光点。",
    prompt:
      "夜晚旧式客厅，雨水落在大窗上，窗外城市灯火虚化，一盏暖色台灯照亮桌椅，空间安静无人，固定镜头，低调光。",
  },
  {
    id: "night-passenger",
    title: "夜车窗边",
    image: "/images/night-passenger.png",
    duration: "00:10",
    kind: "分镜",
    type: "短片",
    emotion: "孤独",
    lighting: "蓝调时刻",
    movement: "固定镜头",
    tags: ["人物侧脸", "车窗", "城市散景", "倒影"],
    description: "夜车穿过城市，窗边的人看着雨滴与灯光向后滑去。",
    prompt:
      "夜间列车内，年轻东亚女性侧脸望向雨湿车窗，玻璃中有轻微倒影，城市红黄散景从窗外掠过，克制表情，浅景深，电影肖像。",
  },
  {
    id: "night-rain-street",
    title: "雨巷独行",
    image: "/images/night-rain-street.png",
    duration: "00:11",
    kind: "视频",
    type: "纪录片",
    emotion: "孤独",
    lighting: "硬光",
    movement: "跟镜头",
    tags: ["雨巷", "独行者", "霓虹反射", "纵深"],
    description: "一名行人穿过老城雨巷，招牌的红光在积水中拉成长长倒影。",
    prompt:
      "雨夜老城窄街，一名人物背对镜头走在中央，湿润路面反射暖黄与暗红招牌，单点透视，低机位缓慢跟随，黑色电影气质。",
  },
  {
    id: "night-film-reel",
    title: "胶片余温",
    image: "/images/night-film-reel.png",
    duration: "00:06",
    kind: "分镜",
    type: "广告",
    emotion: "怀旧",
    lighting: "室内暖光",
    movement: "固定镜头",
    tags: ["胶片盘", "微距", "金属", "钨丝灯"],
    description: "旧胶片盘在钨丝灯下泛着暖光，齿孔与划痕清晰可见。",
    prompt:
      "老式金属胶片盘与散开的35mm胶片，微距特写，钨丝灯暖色轮廓光，深色背景，金属磨损纹理清晰，固定镜头，浅景深。",
  },
];
