export const filterGroups = [
  {
    key: "type",
    label: "类型",
    options: ["全部", "故事片", "广告", "纪录片", "短片", "动画", "实验影像"],
  },
  {
    key: "emotion",
    label: "情绪",
    options: ["全部", "温暖", "宁静", "怀旧", "孤独", "希望", "紧张", "治愈"],
  },
  {
    key: "lighting",
    label: "光影",
    options: [
      "全部",
      "自然光",
      "黄金时刻",
      "蓝调时刻",
      "室内暖光",
      "逆光",
      "柔光",
      "硬光",
    ],
  },
  {
    key: "movement",
    label: "运镜",
    options: ["全部", "固定镜头", "推镜头", "拉镜头", "摇镜头", "跟镜头", "升降镜头", "航拍"],
  },
];

export const storyboardItems = [
  {
    id: "night-cinema",
    title: "雨夜老电影院",
    image: "/images/night-cinema.png",
    duration: "00:12",
    kind: "视频",
    type: "故事片",
    emotion: "温暖",
    lighting: "自然光",
    movement: "固定镜头",
    tags: ["孤独", "低调光", "固定镜头", "室外", "夜晚街道"],
    description:
      "老电影院的雨夜，霓虹与路灯映在湿润的地面，空气里有潮湿与旧胶片的味道。一个人走在街道上，光影在脚下碎裂又重组。",
    prompt:
      "雨夜，老电影院门口，霓虹灯与路灯反射在湿漉漉的地面，孤独的人影，低调光，胶片质感，街道寂静，35mm 电影质感，浅景深，长焦压缩空间，缓慢推进。",
  },
  {
    id: "night-projector",
    title: "放映室的光",
    image: "/images/night-projector.png",
    duration: "00:15",
    kind: "视频",
    type: "纪录片",
    emotion: "怀旧",
    lighting: "硬光",
    movement: "推镜头",
    tags: ["放映机", "体积光", "剪影", "旧胶片"],
    description: "放映机的光束穿过尘埃，操作员与老式胶片盘沉在暗部里。",
    prompt:
      "昏暗老式放映室，人物背影位于画面左侧，放映机射出强烈体积光，尘埃颗粒可见，右侧有大型金属胶片盘，低调光，电影质感。",
  },
  {
    id: "night-lounge",
    title: "雨窗旧厅",
    image: "/images/night-lounge.png",
    duration: "00:08",
    kind: "分镜",
    type: "故事片",
    emotion: "温暖",
    lighting: "室内暖光",
    movement: "固定镜头",
    tags: ["旧公寓", "台灯", "雨窗", "暖光"],
    description: "无人坐下的旧客厅只亮着台灯，雨后的城市在窗外化成柔软光点。",
    prompt:
      "夜晚旧式客厅，雨水落在大窗上，窗外城市灯火虚化，一盏暖色台灯照亮桌椅，空间安静无人，固定镜头，低调光。",
  },
  {
    id: "night-passenger",
    title: "夜车窗边",
    image: "/images/night-passenger.png",
    duration: "00:10",
    kind: "分镜",
    type: "短片",
    emotion: "孤独",
    lighting: "蓝调时刻",
    movement: "固定镜头",
    tags: ["人物侧脸", "车窗", "城市散景", "倒影"],
    description: "夜车穿过城市，窗边的人看着雨滴与灯光向后滑去。",
    prompt:
      "夜间列车内，年轻东亚女性侧脸望向雨湿车窗，玻璃中有轻微倒影，城市红黄散景从窗外掠过，克制表情，浅景深，电影肖像。",
  },
  {
    id: "night-rain-street",
    title: "雨巷独行",
    image: "/images/night-rain-street.png",
    duration: "00:11",
    kind: "视频",
    type: "纪录片",
    emotion: "孤独",
    lighting: "硬光",
    movement: "跟镜头",
    tags: ["雨巷", "独行者", "霓虹反射", "纵深"],
    description: "一名行人穿过老城雨巷，招牌的红光在积水中拉成长长倒影。",
    prompt:
      "雨夜老城窄街，一名人物背对镜头走在中央，湿润路面反射暖黄与暗红招牌，单点透视，低机位缓慢跟随，黑色电影气质。",
  },
  {
    id: "night-film-reel",
    title: "胶片余温",
    image: "/images/night-film-reel.png",
    duration: "00:06",
    kind: "分镜",
    type: "广告",
    emotion: "怀旧",
    lighting: "室内暖光",
    movement: "固定镜头",
    tags: ["胶片盘", "微距", "金属", "钨丝灯"],
    description: "旧胶片盘在钨丝灯下泛着暖光，齿孔与划痕清晰可见。",
    prompt:
      "老式金属胶片盘与散开的35mm胶片，微距特写，钨丝灯暖色轮廓光，深色背景，金属磨损纹理清晰，固定镜头，浅景深。",
  },
];
